### ISSUE TITLE
AdGuard prevents users from logging in to https://e-tjanster.1177.se 

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/HttpsExclusions#199]
Reported by helpdesk id 2304542.

I did try to add "1177.se" to the HTTPS exclusion list, and that makes the problem go away.

**Comment by hcgpalm** [comment]
See also https://github.com/AdguardTeam/AdguardFilters/issues/40642

While adding 1177.se to the HTTPS exclusion list makes the problem go away, it doesn't explain why AdGuard prevents it from working correctly. It seems to be an issue with the AdGuard proxy.
It would be great if you could tell us how to work around the problem on the server side since quite a few users seems to be affected by this issue.
