### ISSUE TITLE
HTTPS Exclusions - Indonesian wallets

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/HttpsExclusions#363]
Reported by: 2223291

https://play.google.com/store/apps/details?id=id.dana (With DANA, you can make non-cash and even non-card transactions for your daily needs, from offline payment transactions to paying bills & installments online)

https://play.google.com/store/apps/details?id=com.grabtaxi.passenger (Grab is Southeast Asia's # 1 ride-hailing app, food delivery service, and cashless payment solution all in one)

https://play.google.com/store/apps/details?id=ovo.id (Pay everything and everywhere, with OVO!)

https://play.google.com/store/apps/details?id=com.gojek.app (also some kind of all-in-one wallet)

**Comment by Hafidzgtg** [comment]
Awesome, thank you so much! 🙏🏻
🤦🏻‍♂️almost forget..
This too

![Screenshot_2021-01-02-18-06-10-165_com android vending](https://user-images.githubusercontent.com/50311982/103478259-de7e1d80-4df7-11eb-95ca-87dfbe6a72d7.jpg)
![Screenshot_2021-01-02-18-05-33-682_com android vending](https://user-images.githubusercontent.com/50311982/103478260-e2aa3b00-4df7-11eb-81b4-48726b5d26f3.jpg)
![Screenshot_2021-01-02-18-05-15-518_com android vending](https://user-images.githubusercontent.com/50311982/103478265-e5a52b80-4df7-11eb-9f51-560defe0726d.jpg)
![Screenshot_2021-01-02-18-05-04-504_com android vending](https://user-images.githubusercontent.com/50311982/103478266-e6d65880-4df7-11eb-9e3a-bb5448d76c35.jpg)

**Comment by bkrucarci** [comment]
@ameshkov any update on this?

**Comment by Hafidzgtg** [comment]
and this too....
![IMG_20220513_200621](https://user-images.githubusercontent.com/50311982/168289939-671a61ee-c4f0-44a8-bc2a-6c82d73785cc.jpg)
![IMG_20220513_200634](https://user-images.githubusercontent.com/50311982/168289949-df1f84e5-a400-4787-b268-2f0a45174a5a.jpg)

**Comment by ameshkov** [comment]
@bkrucarci @Hafidzgtg it's rather hard to reproduce the issue on our side, could you please check AdGuard's filtering log and grab the domains the apps try to connect to.

@zzebrum please don't forget about this one.

**Comment by Alex-302** [comment]
But HTTPS traffic of these apps on Android is not filtered anyway.
For web version can be used `danamon.co.id` 
All their subdomains:
https://subdomainfinder.c99.nl/scans/2022-05-17/danamon.co.id

@Hafidzgtg Why not to post the links instead of screenshots?

**Comment by Hafidzgtg** [comment]
ah you're right.. i don't think this is haha ​​okay this is the bank link of all below..

https://play.google.com/store/apps/details?id=com.bsm.activity2

https://play.google.com/store/apps/details?id=id.dana

https://play.google.com/store/apps/details?id=com.btpn.dc

https://play.google.com/store/apps/details?id=id.flip

https://play.google.com/store/apps/details?id=com.gojek.app

https://play.google.com/store/apps/details?id=com.grabtaxi.passenger

https://play.google.com/store/apps/details?id=src.com.bni

https://play.google.com/store/apps/details?id=id.bmri.livin

https://play.google.com/store/apps/details?id=com.tokopedia.tkpd

https://play.google.com/store/apps/details?id=com.shopee.id

https://play.google.com/store/apps/details?id=com.lazada.android

https://play.google.com/store/apps/details?id=blibli.mobile.commerce

https://play.google.com/store/apps/details?id=jd.cdyjy.overseas.market.indonesia

Hopefully all of this is whitelisted🙏🏻 because it's all about payment and paid buyers thank you very much🙏🏻..

**Comment by Alex-302** [comment]
Only 4 apps are related to banking
https://play.google.com/store/apps/details?id=com.bsm.activity2
https://play.google.com/store/apps/details?id=id.dana
https://play.google.com/store/apps/details?id=id.flip
https://play.google.com/store/apps/details?id=src.com.bni

Domains to exclude:
```
bsm.co.id
bankbsi.co.id
dana.id
flip.id
bni.co.id
danamon.co.id
```
